export type SectorIssue = { t: string; d: string };
export type SectorFaq = { q: string; a: string };
export type SectorCopy = { title: string; short: string; intro: string; issues: SectorIssue[]; faqs: SectorFaq[] };
export type Sector = {
  slug: string;
  ar: SectorCopy;
  en: SectorCopy;
  /** Slugs of service pages (core pillars or specialised lines) most relevant to the sector. */
  services: string[];
  /** Slugs of blog articles worth reading next. */
  articles: string[];
};

export const sectors: Sector[] = [
  {
    slug: "construction",
    services: ["real-estate-construction", "corporate-contracts", "disputes-arbitration", "government-contracts"],
    articles: ["commercial-contract-review-before-signing", "breach-of-contract-damages-saudi-arabia", "liquidated-damages-saudi-arabia", "arbitration-clause-commercial-contracts-saudi-arabia"],
    ar: {
      title: "الإنشاءات والمقاولات",
      short: "عقود المقاولة والتوريد والمطالبات والتحكيم لمشاريع البناء والبنية التحتية في المملكة.",
      intro: "قطاع الإنشاءات من أكثر القطاعات اعتمادًا على العقود المعقدة وسلاسل التوريد والمدد الزمنية الحرجة. نواكب المقاولين والملّاك والاستشاريين والموردين من تأسيس المشروع وصياغة العقد إلى إدارة التغييرات والمطالبات وتسوية النزاع، بما يحمي الجدول الزمني والتدفق النقدي والحقوق التعاقدية.",
      issues: [
        { t: "عقود المقاولة والمقاولة من الباطن", d: "صياغة ومراجعة شروط الأعمال والدفعات والتسليم والضمانات وتوزيع المخاطر بين الأطراف." },
        { t: "أوامر التغيير والمطالبات", d: "توثيق التغييرات وإدارة مطالبات التمديد والتكاليف الإضافية قبل أن تتحول إلى نزاع." },
        { t: "التأخير وغرامات التأخير", d: "تقييم أسباب التأخير ومسؤولية كل طرف، والدفاع عن غرامات التأخير أو المطالبة بها." },
        { t: "الضمانات والمستخلصات", d: "ضمانات حسن التنفيذ والدفعة المقدمة والاحتجازات، والمطالبة بالمستحقات المتأخرة." },
        { t: "المنازعات والتحكيم", d: "تمثيل الأطراف أمام الجهات القضائية وهيئات التحكيم في منازعات المشاريع." },
      ],
      faqs: [
        { q: "متى يحق للمقاول المطالبة بتمديد المدة؟", a: "يعتمد ذلك على نصوص العقد والإخطارات المطلوبة وسبب التأخير. من المهم توثيق الحدث كتابيًا وفي المدة التي يحددها العقد قبل تقديم المطالبة." },
        { q: "هل يمكن تخفيض غرامة التأخير؟", a: "قد يكون ذلك ممكنًا إذا كان التأخير ناتجًا عن الطرف الآخر أو كانت الغرامة مبالغًا فيها قياسًا بالضرر الفعلي. يُقدَّر ذلك بحسب وقائع كل حالة." },
        { q: "أي مسار أنسب: التقاضي أم التحكيم؟", a: "يتحدد غالبًا بشرط تسوية النزاعات في العقد، وبحجم النزاع وسرعة الحسم المطلوبة وطبيعة الأدلة. نراجع الشرط ونقترح المسار المناسب." },
      ],
    },
    en: {
      title: "Construction & Contracting",
      short: "Construction, supply, claims and arbitration for building and infrastructure projects in the Kingdom.",
      intro: "Construction runs on complex contracts, supply chains and critical timelines. We support contractors, owners, consultants and suppliers from structuring the project and drafting the contract through managing variations and claims to resolving disputes — protecting the programme, cash flow and contractual rights.",
      issues: [
        { t: "Construction and subcontract agreements", d: "Drafting and reviewing scope, payment, handover, warranties and risk allocation." },
        { t: "Variations and claims", d: "Documenting changes and managing extension-of-time and cost claims before they become disputes." },
        { t: "Delay and liquidated damages", d: "Assessing causes of delay and each party's responsibility; defending or pursuing delay damages." },
        { t: "Bonds, certificates and retention", d: "Performance and advance-payment guarantees, retention, and recovery of overdue payments." },
        { t: "Disputes and arbitration", d: "Representing parties before courts and arbitral tribunals in project disputes." },
      ],
      faqs: [
        { q: "When can a contractor claim an extension of time?", a: "It depends on the contract terms, the notices required and the cause of delay. Record the event in writing and within the contractual period before submitting the claim." },
        { q: "Can liquidated damages be reduced?", a: "Possibly, where the delay was caused by the other party or the amount is out of proportion to the actual loss. It is assessed on the facts of each case." },
        { q: "Court or arbitration?", a: "Usually set by the dispute-resolution clause, the size of the dispute, the speed needed and the nature of the evidence. We review the clause and recommend the route." },
      ],
    },
  },
  {
    slug: "technology",
    services: ["technology-data", "personal-data-protection", "intellectual-property", "cyber-crime"],
    articles: ["personal-data-protection-obligations-saudi-arabia", "commercial-contract-review-before-signing", "memorandum-of-understanding-saudi-arabia", "shareholders-agreement-saudi-arabia"],
    ar: {
      title: "التقنية والتحول الرقمي",
      short: "عقود التقنية وحماية البيانات والملكية الفكرية والشركات الناشئة والمنصات الرقمية.",
      intro: "تعمل شركات التقنية في بيئة تنظيمية تتجدد باستمرار: بيانات شخصية، ومنصات، ومدفوعات، وملكية فكرية، وجولات تمويل. نقدّم لها مشورة عملية تُبقي المنتج متوافقًا مع الأنظمة وتحمي الأصول غير الملموسة وتُسهّل الاستثمار والنمو.",
      issues: [
        { t: "حماية البيانات الشخصية", d: "سياسات الخصوصية وأسس المعالجة والموافقة وحقوق أصحاب البيانات والإبلاغ عن التسرب." },
        { t: "عقود البرمجيات والخدمات السحابية", d: "اتفاقيات الترخيص ومستوى الخدمة والملكية والمسؤولية والخروج من العقد." },
        { t: "الملكية الفكرية", d: "تسجيل العلامات وحماية الشيفرة والأسرار التجارية وتنظيم ملكية ما ينتجه الموظفون والمقاولون." },
        { t: "الشركات الناشئة والتمويل", d: "تأسيس الشركة واتفاقيات المساهمين وجولات الاستثمار وخيارات الموظفين." },
        { t: "المنصات والتجارة الإلكترونية", d: "شروط الاستخدام وحماية المستهلك والتراخيص المرتبطة بنشاط المنصة." },
      ],
      faqs: [
        { q: "هل يجب أن تكون لشركتي سياسة خصوصية؟", a: "نعم في الغالب إذا كانت الشركة تجمع بيانات شخصية. يجب أن تعكس السياسة الممارسة الفعلية وأن تتوافق مع نظام حماية البيانات الشخصية." },
        { q: "من يملك الشيفرة التي كتبها مطوّر مستقل؟", a: "يتحدد بنص العقد. إن لم يتضمن العقد نقلًا واضحًا للملكية فقد تبقى الحقوق لدى المطوّر، لذا يُنصّ على ذلك صراحة." },
        { q: "ما الذي يجب تجهيزه قبل جولة استثمار؟", a: "مستندات التأسيس وسجل المساهمين وعقود الموظفين والمطورين وسندات الملكية الفكرية والعقود الجوهرية، لتقليل أسئلة العناية القانونية." },
      ],
    },
    en: {
      title: "Technology & Digital Transformation",
      short: "Technology contracts, data protection, IP, start-ups and digital platforms.",
      intro: "Technology companies operate under a constantly changing regulatory landscape: personal data, platforms, payments, IP and funding rounds. We give practical advice that keeps the product compliant, protects intangible assets and makes investment and growth easier.",
      issues: [
        { t: "Personal data protection", d: "Privacy policies, lawful bases, consent, data-subject rights and breach notification." },
        { t: "Software and cloud agreements", d: "Licences, service levels, ownership, liability and exit." },
        { t: "Intellectual property", d: "Trade-mark registration, protecting code and trade secrets, and allocating ownership of what staff and contractors create." },
        { t: "Start-ups and funding", d: "Incorporation, shareholders' agreements, investment rounds and employee options." },
        { t: "Platforms and e-commerce", d: "Terms of use, consumer protection and the licences tied to the platform's activity." },
      ],
      faqs: [
        { q: "Does my company need a privacy policy?", a: "Usually yes if it collects personal data. The policy must reflect actual practice and comply with the Personal Data Protection Law." },
        { q: "Who owns code written by a freelance developer?", a: "The contract decides. Without a clear transfer of ownership the rights may stay with the developer, so it should be stated expressly." },
        { q: "What should be ready before an investment round?", a: "Constitutional documents, the share register, staff and developer contracts, IP records and key contracts, to reduce diligence questions." },
      ],
    },
  },
  {
    slug: "education",
    services: ["compliance-governance", "employment-labor", "corporate-contracts", "intellectual-property"],
    articles: ["employer-terminate-employment-without-reason-saudi-arabia", "end-of-employment-entitlements-saudi-arabia", "commercial-contract-review-before-signing"],
    ar: {
      title: "التعليم",
      short: "ترخيص المنشآت التعليمية والعقود والعلاقات العمالية وحماية بيانات الطلاب.",
      intro: "تتطلب المنشآت التعليمية الأهلية والتدريبية امتثالًا دقيقًا لمتطلبات الجهات المنظمة وعقودًا واضحة مع أولياء الأمور والمعلمين والموردين. نساعدها على بناء إطار قانوني يحمي سمعتها ويُنظّم علاقاتها.",
      issues: [
        { t: "التراخيص والاعتمادات", d: "متطلبات الترخيص والاعتماد والتجديد والعلاقة مع الجهات المنظمة للتعليم والتدريب." },
        { t: "العقود مع أولياء الأمور والطلاب", d: "عقود التسجيل والرسوم والاسترداد وسياسات الانضباط والتظلم." },
        { t: "العمل والتوظيف", d: "عقود المعلمين والإداريين والإنهاء وحقوق نهاية الخدمة." },
        { t: "حماية بيانات الطلاب", d: "جمع بيانات القاصرين ومعالجتها ومشاركتها مع المنصات التعليمية." },
        { t: "الملكية الفكرية والمحتوى", d: "ملكية المناهج والمحتوى الرقمي وتراخيص المنصات التعليمية." },
      ],
      faqs: [
        { q: "هل تلزم سياسة استرداد الرسوم بنص مكتوب؟", a: "الأفضل أن تُنص سياسة الاسترداد وشروطها بوضوح في عقد التسجيل لتجنب النزاع وإثبات علم ولي الأمر بها." },
        { q: "كيف نتعامل مع بيانات الطلاب القاصرين؟", a: "تُعالج في أضيق نطاق لازم وبأساس نظامي واضح، مع ضوابط للوصول والمشاركة وفق نظام حماية البيانات الشخصية." },
        { q: "من يملك المحتوى الذي يعدّه المعلم؟", a: "يتحدد بعقد العمل وسياسة المنشأة. يُوصى بالنص صراحة على ملكية المواد التعليمية المنتجة أثناء العمل." },
      ],
    },
    en: {
      title: "Education",
      short: "Licensing of educational institutions, contracts, employment and student-data protection.",
      intro: "Private schools, institutes and training providers need precise compliance with regulators' requirements and clear contracts with parents, teachers and suppliers. We help build a legal framework that protects their reputation and structures their relationships.",
      issues: [
        { t: "Licences and accreditation", d: "Licensing, accreditation and renewal requirements and the relationship with education and training regulators." },
        { t: "Contracts with parents and students", d: "Enrolment contracts, fees, refunds, discipline and grievance policies." },
        { t: "Employment", d: "Teacher and administrative contracts, termination and end-of-service entitlements." },
        { t: "Student data protection", d: "Collecting, processing and sharing minors' data with learning platforms." },
        { t: "IP and content", d: "Ownership of curricula and digital content and licences for learning platforms." },
      ],
      faqs: [
        { q: "Should a fee-refund policy be in writing?", a: "Yes — set the refund policy and its conditions out clearly in the enrolment contract to avoid disputes and prove the parent's knowledge." },
        { q: "How should students' data be handled?", a: "In the narrowest scope necessary and on a clear lawful basis, with controls on access and sharing under the Personal Data Protection Law." },
        { q: "Who owns content a teacher creates?", a: "The employment contract and the institution's policy decide. State expressly who owns teaching material produced during employment." },
      ],
    },
  },
  {
    slug: "healthcare",
    services: ["healthcare-pharma", "compliance-governance", "insurance", "personal-data-protection"],
    articles: ["personal-data-protection-obligations-saudi-arabia", "due-diligence-before-commercial-deal-saudi-arabia", "commercial-contract-review-before-signing"],
    ar: {
      title: "الرعاية الصحية",
      short: "تراخيص المنشآت الصحية والمستحضرات والتأمين الطبي وحماية البيانات الصحية والمسؤولية.",
      intro: "يخضع القطاع الصحي والدوائي لرقابة متعددة الجهات وإلى التزامات صارمة تجاه المرضى والبيانات الصحية. نقدّم للمنشآت الصحية وشركات الأدوية والأجهزة الطبية والتقنية الصحية مشورة تجمع بين الامتثال التنظيمي وحماية العلاقات التجارية.",
      issues: [
        { t: "ترخيص المنشآت والمنتجات", d: "متطلبات تراخيص المنشآت الصحية وتسجيل المستحضرات والأجهزة الطبية والجهات المختصة." },
        { t: "العلاقة مع شركات التأمين", d: "اتفاقيات شبكات مقدمي الخدمة والمطالبات والمنازعات مع شركات التأمين." },
        { t: "البيانات الصحية", d: "سرية بيانات المرضى وأسس معالجتها ومشاركتها وضوابط التقنية الصحية." },
        { t: "المسؤولية المهنية والعقود", d: "عقود الممارسين والتوريد والتوزيع وإدارة المخاطر والمطالبات." },
        { t: "الشراكات والاستثمار", d: "الشراكات مع المستثمرين والاستحواذ على المنشآت الصحية والعناية القانونية." },
      ],
      faqs: [
        { q: "هل تُعد البيانات الصحية بيانات حساسة؟", a: "نعم، فهي من أكثر أنواع البيانات حساسية وتتطلب ضوابط أشد في الجمع والتخزين والمشاركة ومدة الاحتفاظ." },
        { q: "ما أهم بند في عقد التوريد الطبي؟", a: "مواصفات المنتج والتسجيل لدى الجهة المختصة وضمان الجودة وتحمل المسؤولية في حال العيب والاسترجاع." },
        { q: "كيف تُدار مطالبات شركات التأمين المرفوضة؟", a: "بمراجعة اتفاقية الشبكة وأسباب الرفض والمستندات الطبية، ثم المطالبة الودية أو الإجراءات النظامية المناسبة." },
      ],
    },
    en: {
      title: "Healthcare",
      short: "Licensing of health facilities and products, medical insurance, health-data protection and liability.",
      intro: "Healthcare and pharma are supervised by several regulators and carry strict duties towards patients and health data. We advise health facilities, pharmaceutical and device companies and health-tech businesses, combining regulatory compliance with protection of their commercial relationships.",
      issues: [
        { t: "Facility and product licensing", d: "Licensing requirements for health facilities and registration of medicines and devices with the competent authorities." },
        { t: "Dealings with insurers", d: "Provider-network agreements, claims and disputes with insurance companies." },
        { t: "Health data", d: "Patient confidentiality, lawful bases for processing and sharing, and health-tech safeguards." },
        { t: "Professional liability and contracts", d: "Practitioner, supply and distribution contracts, risk management and claims." },
        { t: "Partnerships and investment", d: "Investor partnerships, acquisitions of health facilities and legal due diligence." },
      ],
      faqs: [
        { q: "Is health data sensitive data?", a: "Yes — it is among the most sensitive categories and needs tighter controls on collection, storage, sharing and retention." },
        { q: "What is the key clause in a medical supply contract?", a: "Product specifications, registration with the competent authority, quality assurance and responsibility for defects and recalls." },
        { q: "How are rejected insurance claims handled?", a: "By reviewing the network agreement, the grounds for rejection and the medical records, then amicable demand or the appropriate formal procedure." },
      ],
    },
  },
  {
    slug: "sports-entertainment",
    services: ["sports-entertainment", "intellectual-property", "corporate-contracts", "disputes-arbitration"],
    articles: ["commercial-contract-review-before-signing", "arbitration-clause-commercial-contracts-saudi-arabia", "memorandum-of-understanding-saudi-arabia"],
    ar: {
      title: "الرياضة والترفيه",
      short: "عقود الرعاية والبث والتراخيص والأندية والفعاليات والملكية الفكرية في الرياضة والترفيه.",
      intro: "يشهد قطاع الرياضة والترفيه نموًا متسارعًا يستدعي عقودًا دقيقة للرعاية والبث والفعاليات وإدارة الحقوق. نساعد الأندية والمنظمين والشركات والرعاة على تنظيم علاقاتهم وحماية حقوقهم التجارية.",
      issues: [
        { t: "عقود الرعاية والإعلان", d: "نطاق الحقوق والمقابل والحصرية والالتزامات الترويجية وإنهاء العقد." },
        { t: "حقوق البث والمحتوى", d: "ترخيص الحقوق ومدتها ونطاقها الجغرافي وحمايتها من التعدي." },
        { t: "تراخيص الفعاليات", d: "الأذونات والاشتراطات النظامية وعقود الموقع والموردين وسلامة الحضور." },
        { t: "عقود اللاعبين والمواهب", d: "تنظيم العلاقة التعاقدية والحقوق التجارية وحقوق الصورة." },
        { t: "العلامات والملكية الفكرية", d: "تسجيل الشعارات والعلامات وحماية البضائع والمنتجات المرخصة." },
      ],
      faqs: [
        { q: "ما أهم ما يُنص عليه في عقد الرعاية؟", a: "نطاق الحقوق والمقابل والحصرية والمدة وحالات الإنهاء والتعويض عند الإخلال، مع تحديد ما يُعد استخدامًا مسموحًا للعلامة." },
        { q: "هل يمكن حماية حقوق الصورة؟", a: "نعم بالنص عليها في العقد وبتنظيم استخدام الاسم والصورة والتجارة بهما ضمن حدود واضحة." },
        { q: "ما مخاطر تنظيم فعالية دون تراخيص؟", a: "قد تشمل إيقاف الفعالية وغرامات ومسؤولية تجاه الحضور والموردين، لذا تُستكمل الاشتراطات النظامية مسبقًا." },
      ],
    },
    en: {
      title: "Sports & Entertainment",
      short: "Sponsorship, broadcasting, licensing, clubs, events and IP in sport and entertainment.",
      intro: "Sport and entertainment are growing fast and call for precise sponsorship, broadcast, event and rights-management contracts. We help clubs, organisers, companies and sponsors structure their relationships and protect their commercial rights.",
      issues: [
        { t: "Sponsorship and advertising", d: "Scope of rights, consideration, exclusivity, promotional commitments and termination." },
        { t: "Broadcast and content rights", d: "Licensing rights, term, territory and protection against infringement." },
        { t: "Event permits", d: "Approvals and statutory requirements, venue and supplier contracts, and audience safety." },
        { t: "Player and talent contracts", d: "Structuring the contractual relationship, commercial rights and image rights." },
        { t: "Marks and IP", d: "Registering logos and marks and protecting licensed merchandise." },
      ],
      faqs: [
        { q: "What matters most in a sponsorship agreement?", a: "The scope of rights, consideration, exclusivity, term, termination events and remedies for breach, with clear rules on permitted use of the mark." },
        { q: "Can image rights be protected?", a: "Yes — by providing for them in the contract and regulating use of name and image within clear limits." },
        { q: "What are the risks of an event without permits?", a: "Possible suspension, fines and liability to attendees and suppliers, so statutory requirements should be completed beforehand." },
      ],
    },
  },
  {
    slug: "hospitality-tourism",
    services: ["corporate-contracts", "franchise", "employment-labor", "compliance-governance"],
    articles: ["commercial-contract-review-before-signing", "residential-lease-check-before-signing-saudi-arabia", "commercial-contract-termination-saudi-arabia"],
    ar: {
      title: "الضيافة والسياحة",
      short: "عقود إدارة الفنادق والامتياز والإيجار وتراخيص السياحة والعمالة في قطاع الضيافة.",
      intro: "ينمو قطاع الضيافة والسياحة بفعل المشاريع الكبرى والوجهات الجديدة، ويعتمد على عقود إدارة وتشغيل وامتياز وإيجار طويلة الأمد. نساعد الملّاك والمشغّلين والمستثمرين على تنظيم هذه العلاقات وتقليل مخاطرها.",
      issues: [
        { t: "عقود إدارة وتشغيل الفنادق", d: "الرسوم والأداء ومؤشراته والصلاحيات والإنهاء وحقوق الملّاك." },
        { t: "الامتياز التجاري", d: "اتفاقيات الامتياز وإفصاحات المانح وحماية العلامة ونقل المعرفة." },
        { t: "الإيجار والمواقع", d: "عقود الإيجار طويلة الأجل وإعادة التفاوض وإنهاء الإيجار والإخلاء." },
        { t: "التراخيص والامتثال", d: "تراخيص المنشآت السياحية واشتراطات الجودة والسلامة." },
        { t: "العمالة والتوظيف", d: "عقود العاملين والتوطين وانتهاء الخدمة والمنازعات العمالية." },
      ],
      faqs: [
        { q: "ما الفرق بين عقد الإدارة وعقد الامتياز؟", a: "في الإدارة يتولى المشغّل تشغيل الفندق نيابة عن المالك مقابل رسوم، أما الامتياز فيمنح حق استخدام العلامة والنظام التشغيلي مع بقاء الإدارة لدى المستثمر." },
        { q: "كيف نحمي المالك في عقد الإدارة؟", a: "بمؤشرات أداء واضحة وحقوق مراجعة مالية وحق إنهاء عند ضعف الأداء وقيود على الصلاحيات المالية." },
        { q: "ما أهم بنود إيجار الموقع التجاري؟", a: "المدة وآلية تعديل الأجرة والصيانة والتنازل أو التأجير من الباطن وحالات الإنهاء والإخلاء." },
      ],
    },
    en: {
      title: "Hospitality & Tourism",
      short: "Hotel management, franchise and lease agreements, tourism licensing and staffing in hospitality.",
      intro: "Hospitality and tourism are growing with giga-projects and new destinations, and rely on long-term management, operating, franchise and lease agreements. We help owners, operators and investors structure these relationships and reduce their risks.",
      issues: [
        { t: "Hotel management and operating agreements", d: "Fees, performance and KPIs, authority, termination and owners' rights." },
        { t: "Franchising", d: "Franchise agreements, franchisor disclosure, brand protection and know-how transfer." },
        { t: "Leases and sites", d: "Long-term leases, renegotiation, termination and eviction." },
        { t: "Licensing and compliance", d: "Tourism-facility licences and quality and safety requirements." },
        { t: "Staffing and employment", d: "Employment contracts, localisation, end of service and labour disputes." },
      ],
      faqs: [
        { q: "How does a management agreement differ from a franchise?", a: "Under management the operator runs the hotel for the owner for a fee; a franchise licenses the brand and operating system while the investor keeps management." },
        { q: "How do we protect the owner in a management agreement?", a: "Clear performance indicators, financial audit rights, a right to terminate on poor performance and limits on financial authority." },
        { q: "What matters in a commercial lease?", a: "Term, rent-review mechanism, maintenance, assignment or sub-letting, and termination and eviction events." },
      ],
    },
  },
  {
    slug: "transport-logistics",
    services: ["transport-logistics-aviation", "corporate-contracts", "insurance", "disputes-arbitration"],
    articles: ["commercial-contract-review-before-signing", "force-majeure-exceptional-circumstances-saudi-arabia", "breach-of-contract-damages-saudi-arabia"],
    ar: {
      title: "النقل والخدمات اللوجستية",
      short: "عقود النقل والشحن والتخزين والتأمين والجمارك والطيران والمنازعات اللوجستية.",
      intro: "تعتمد سلاسل الإمداد على عقود واضحة للنقل والشحن والتخزين والتوزيع. ويتقاطع القطاع مع الجمارك والتأمين والمسؤولية عن الأضرار والتأخير. نساعد شركات النقل والشحن والمصنّعين والمستوردين على تنظيم المخاطر وحماية حقوقهم.",
      issues: [
        { t: "عقود النقل والشحن", d: "الشروط والمسؤولية عن الفقد والتلف والتأخير والحد الأعلى للتعويض." },
        { t: "التخزين والتوزيع", d: "اتفاقيات المستودعات والخدمات اللوجستية وحدود المسؤولية." },
        { t: "التأمين والمطالبات", d: "التأمين على البضائع والمطالبات ضد الناقل أو شركة التأمين." },
        { t: "الجمارك والتراخيص", d: "المتطلبات الجمركية وتراخيص النقل والتصنيف والإفراج." },
        { t: "القوة القاهرة والتأخير", d: "تقييم أثر الظروف الاستثنائية على الالتزامات والتأخير." },
      ],
      faqs: [
        { q: "من يتحمل تلف البضاعة أثناء النقل؟", a: "يتحدد بعقد النقل والشروط المتفق عليها وبحدود مسؤولية الناقل ووثائق التأمين، ولذا تُراجع هذه الوثائق قبل الشحن." },
        { q: "هل تُعد الأزمات قوة قاهرة تُعفي من التأخير؟", a: "ليس تلقائيًا؛ يلزم أن تتوافر شروطها النظامية والتعاقدية وأن يثبت الأثر المباشر على التنفيذ." },
        { q: "ما مستندات المطالبة بتعويض عن تلف الشحنة؟", a: "عقد النقل وبوليصة الشحن ومحضر الاستلام والصور وتقارير المعاينة وفواتير قيمة البضاعة وإخطار الناقل في المدة المحددة." },
      ],
    },
    en: {
      title: "Transport & Logistics",
      short: "Transport, freight, warehousing, insurance, customs, aviation and logistics disputes.",
      intro: "Supply chains depend on clear transport, freight, storage and distribution contracts, where customs, insurance and liability for damage and delay intersect. We help carriers, freight forwarders, manufacturers and importers manage risk and protect their rights.",
      issues: [
        { t: "Transport and freight agreements", d: "Terms, liability for loss, damage and delay, and the ceiling on compensation." },
        { t: "Warehousing and distribution", d: "Warehouse and logistics-services agreements and limits of liability." },
        { t: "Insurance and claims", d: "Cargo insurance and claims against the carrier or insurer." },
        { t: "Customs and licensing", d: "Customs requirements, transport licences, classification and release." },
        { t: "Force majeure and delay", d: "Assessing the effect of exceptional circumstances on obligations and delay." },
      ],
      faqs: [
        { q: "Who bears damage to goods in transit?", a: "The transport contract, the agreed terms, the carrier's limits of liability and the insurance policies decide, so they should be reviewed before shipment." },
        { q: "Does a crisis count as force majeure excusing delay?", a: "Not automatically — its legal and contractual conditions must be met and the direct effect on performance shown." },
        { q: "What documents support a damage claim?", a: "The transport contract, bill of lading, receipt record, photographs, survey reports, invoices for the goods' value and timely notice to the carrier." },
      ],
    },
  },
  {
    slug: "banking-finance",
    services: ["banking-islamic-finance", "capital-markets", "enforcement-recovery", "white-collar-aml"],
    articles: ["claim-outstanding-debt-saudi-arabia", "commercial-contract-receivables-saudi-arabia", "due-diligence-before-commercial-deal-saudi-arabia"],
    ar: {
      title: "الخدمات المصرفية والمالية",
      short: "التمويل المصرفي والإسلامي والضمانات والتنفيذ والامتثال ومكافحة غسل الأموال.",
      intro: "يتطلب القطاع المصرفي والمالي مستوى عاليًا من الامتثال وانضباطًا في توثيق التمويل والضمانات. نقدّم للبنوك وشركات التمويل والمستثمرين والمقترضين مشورة في هيكلة التمويل وصياغته وتنفيذ الضمانات والتحصيل.",
      issues: [
        { t: "هيكلة وصياغة التمويل", d: "اتفاقيات التمويل التقليدي والإسلامي وشروط السحب والتعهدات وحالات التعثر." },
        { t: "الضمانات", d: "الرهن والكفالة والضمانات الشخصية والأسناد لأمر وإجراءات تنفيذها." },
        { t: "التنفيذ والتحصيل", d: "المطالبة بالديون المتعثرة وتنفيذ السندات التنفيذية وإدارة الملفات المتعثرة." },
        { t: "الامتثال ومكافحة غسل الأموال", d: "سياسات اعرف عميلك والإبلاغ والعقوبات والتدريب والمراجعة." },
        { t: "الإفلاس وإعادة الهيكلة", d: "التسويات الوقائية وإعادة الهيكلة وحقوق الدائنين." },
      ],
      faqs: [
        { q: "ما السند الذي يتيح التنفيذ المباشر؟", a: "السندات التنفيذية المنصوص عليها نظامًا كالأحكام والأوراق التجارية الصحيحة، ويُنظر في استيفاء شروطها قبل البدء في التنفيذ." },
        { q: "ما الفرق بين الرهن والكفالة؟", a: "الرهن ضمان عيني على أصل محدد، أما الكفالة فضمان شخصي يلتزم بموجبه الكفيل بالوفاء عند تخلف المدين." },
        { q: "ما التزامات المنشأة المالية في مكافحة غسل الأموال؟", a: "تطبيق إجراءات العناية الواجبة بالعملاء ومراقبة العمليات والإبلاغ عن المشتبه فيه وحفظ السجلات وفق الأنظمة واللوائح." },
      ],
    },
    en: {
      title: "Banking & Finance",
      short: "Conventional and Islamic finance, security, enforcement, compliance and AML.",
      intro: "Banking and finance demand a high level of compliance and disciplined documentation of facilities and security. We advise banks, finance companies, investors and borrowers on structuring and drafting finance, enforcing security and recovery.",
      issues: [
        { t: "Structuring and drafting finance", d: "Conventional and Islamic facility agreements, drawdown conditions, covenants and events of default." },
        { t: "Security", d: "Mortgages, guarantees, personal security, promissory notes and enforcement procedures." },
        { t: "Enforcement and recovery", d: "Pursuing distressed debt, enforcing executory instruments and managing non-performing files." },
        { t: "Compliance and AML", d: "KYC policies, reporting, sanctions, training and review." },
        { t: "Insolvency and restructuring", d: "Preventive settlements, restructuring and creditor rights." },
      ],
      faqs: [
        { q: "Which instrument allows direct enforcement?", a: "Statutory executory instruments such as judgments and valid commercial paper; their conditions are checked before enforcement begins." },
        { q: "What is the difference between a pledge and a guarantee?", a: "A pledge is security over a specific asset; a guarantee is personal, under which the guarantor undertakes to pay if the debtor defaults." },
        { q: "What are a financial institution's AML duties?", a: "Customer due diligence, transaction monitoring, reporting suspicious activity and record-keeping under the applicable laws and regulations." },
      ],
    },
  },
  {
    slug: "telecommunications",
    services: ["technology-data", "personal-data-protection", "compliance-governance", "corporate-contracts"],
    articles: ["personal-data-protection-obligations-saudi-arabia", "commercial-contract-review-before-signing", "conflict-of-interest-policy-governance-saudi-arabia"],
    ar: {
      title: "الاتصالات وتقنية المعلومات",
      short: "ترخيص الاتصالات وعقود البنية التحتية والخدمات المدارة وحماية البيانات والأمن السيبراني.",
      intro: "يعمل قطاع الاتصالات وتقنية المعلومات تحت تنظيم دقيق للترخيص والتشغيل والمنافسة وحماية المستخدم. نخدم مشغّلي الاتصالات ومقدمي الخدمات المدارة ومشاريع البنية التحتية بمشورة تغطي التراخيص والعقود والامتثال.",
      issues: [
        { t: "التراخيص والامتثال التنظيمي", d: "متطلبات الترخيص والتزامات المشغّلين تجاه الجهة المنظمة والمستخدمين." },
        { t: "عقود البنية التحتية والمشاركة", d: "اتفاقيات المواقع والأبراج والربط البيني والمشاركة في الشبكات." },
        { t: "الخدمات المدارة والتعهيد", d: "عقود الخدمات المدارة ومستويات الخدمة والمسؤولية والخروج." },
        { t: "البيانات والأمن السيبراني", d: "التزامات حماية البيانات والاستجابة للحوادث السيبرانية." },
        { t: "المنافسة وحماية المستخدم", d: "الممارسات التجارية وشروط الخدمة وشكاوى المستخدمين." },
      ],
      faqs: [
        { q: "ما أهم بنود عقد الخدمات المدارة؟", a: "نطاق الخدمة ومستويات الأداء والتعويضات عند الإخلال وأمن البيانات وملكية البيانات والانتقال عند إنهاء العقد." },
        { q: "هل نحتاج إلى إخطار الجهات عند حادثة اختراق؟", a: "قد تلزم الإخطارات بحسب طبيعة البيانات والنشاط، وتجب مراجعة الالتزامات النظامية فور اكتشاف الحادثة." },
        { q: "كيف تُنظّم مشاركة الأبراج والمواقع؟", a: "باتفاقية مفصلة للحقوق والرسوم والصيانة والمسؤولية والتأمين ومدة الاتفاق وآلية الإنهاء." },
      ],
    },
    en: {
      title: "Telecommunications & IT",
      short: "Telecom licensing, infrastructure contracts, managed services, data protection and cybersecurity.",
      intro: "Telecommunications and IT operate under detailed rules on licensing, operation, competition and user protection. We serve telecom operators, managed-service providers and infrastructure projects with advice covering licences, contracts and compliance.",
      issues: [
        { t: "Licensing and regulatory compliance", d: "Licence requirements and operators' duties to the regulator and users." },
        { t: "Infrastructure and sharing agreements", d: "Site, tower, interconnection and network-sharing agreements." },
        { t: "Managed services and outsourcing", d: "Managed-service contracts, service levels, liability and exit." },
        { t: "Data and cybersecurity", d: "Data-protection obligations and response to cyber incidents." },
        { t: "Competition and user protection", d: "Commercial practices, service terms and user complaints." },
      ],
      faqs: [
        { q: "What matters most in a managed-services contract?", a: "Scope, performance levels, remedies for breach, data security, data ownership and transition on termination." },
        { q: "Must regulators be notified of a breach?", a: "Notification may be required depending on the data and activity; review the legal obligations as soon as the incident is discovered." },
        { q: "How is tower or site sharing structured?", a: "By a detailed agreement on rights, fees, maintenance, liability, insurance, term and termination." },
      ],
    },
  },
  {
    slug: "retail-trade",
    services: ["franchise", "consumer-protection", "corporate-contracts", "intellectual-property"],
    articles: ["commercial-contract-review-before-signing", "commercial-contract-receivables-saudi-arabia", "claim-outstanding-debt-saudi-arabia", "residential-lease-check-before-signing-saudi-arabia"],
    ar: {
      title: "التجزئة والتجارة",
      short: "عقود التوزيع والامتياز وحماية المستهلك والتجارة الإلكترونية وتحصيل المستحقات التجارية.",
      intro: "يعتمد قطاع التجزئة والتجارة على عقود التوريد والتوزيع والامتياز وعلى الامتثال لحماية المستهلك. نساعد التجار والعلامات التجارية والموزعين والمتاجر الإلكترونية في بناء علاقات تعاقدية سليمة وتحصيل مستحقاتهم.",
      issues: [
        { t: "التوزيع والوكالات", d: "اتفاقيات التوزيع والوكالة والحصرية ونطاق الإقليم وإنهاء العلاقة." },
        { t: "الامتياز التجاري", d: "اتفاقيات الامتياز والإفصاح وحماية العلامة وتنظيم العلاقة بين المانح والممنوح له." },
        { t: "حماية المستهلك", d: "الإعلانات والضمان والاسترجاع وشروط البيع وشكاوى المستهلكين." },
        { t: "التجارة الإلكترونية", d: "شروط الاستخدام وسياسات الإرجاع والدفع وحماية البيانات." },
        { t: "تحصيل المستحقات", d: "مطالبات الديون التجارية والفواتير المتأخرة والتنفيذ." },
      ],
      faqs: [
        { q: "هل يمكن للمتجر الإلكتروني رفض الاسترجاع؟", a: "تحكمه أحكام حماية المستهلك وشروط البيع المعلنة؛ وقد يلزم قبول الاسترجاع في حالات معينة كالعيب أو عدم المطابقة." },
        { q: "كيف نحمي حصرية التوزيع؟", a: "بنص صريح على الحصرية والإقليم والحد الأدنى للمشتريات وآثار الإخلال وأحكام التجديد والإنهاء." },
        { q: "ماذا نفعل مع فواتير متأخرة لعميل تجاري؟", a: "نراجع العقد والفواتير وإثبات التسليم، ثم نوجّه إخطارًا رسميًا فمطالبة ودية فالإجراء النظامي المناسب." },
      ],
    },
    en: {
      title: "Retail & Trade",
      short: "Distribution and franchise agreements, consumer protection, e-commerce and recovery of trade receivables.",
      intro: "Retail and trade rely on supply, distribution and franchise contracts and on consumer-protection compliance. We help merchants, brands, distributors and online stores build sound contractual relationships and recover what they are owed.",
      issues: [
        { t: "Distribution and agency", d: "Distribution, agency and exclusivity agreements, territory and ending the relationship." },
        { t: "Franchising", d: "Franchise agreements, disclosure, brand protection and the franchisor–franchisee relationship." },
        { t: "Consumer protection", d: "Advertising, warranty, returns, sale terms and consumer complaints." },
        { t: "E-commerce", d: "Terms of use, returns and payment policies and data protection." },
        { t: "Recovering receivables", d: "Trade-debt claims, overdue invoices and enforcement." },
      ],
      faqs: [
        { q: "Can an online store refuse a return?", a: "Consumer-protection rules and the published sale terms govern; returns may have to be accepted in cases such as defects or non-conformity." },
        { q: "How do we protect distribution exclusivity?", a: "By an express exclusivity clause, territory, minimum purchases, consequences of breach and renewal and termination terms." },
        { q: "What do we do about overdue invoices from a trade customer?", a: "We review the contract, invoices and proof of delivery, then send a formal notice, an amicable demand and the appropriate legal procedure." },
      ],
    },
  },
  {
    slug: "real-estate",
    services: ["real-estate-construction", "corporate-contracts", "disputes-arbitration", "foreign-investment"],
    articles: ["residential-lease-check-before-signing-saudi-arabia", "due-diligence-before-commercial-deal-saudi-arabia", "power-of-attorney-risks-saudi-arabia", "heirs-dispute-estate-division-saudi-arabia"],
    ar: {
      title: "العقارات",
      short: "البيع والإيجار والتطوير العقاري والتسجيل والاستثمار العقاري والمنازعات.",
      intro: "العقار أصل عالي القيمة تتقاطع فيه أنظمة التسجيل والتطوير والإيجار والملكية. نقدّم للملّاك والمطورين والمستثمرين والمستأجرين مشورة تحمي الصفقة من لحظة التفاوض إلى الإفراغ والتسجيل وتدير النزاعات العقارية.",
      issues: [
        { t: "البيع والشراء والعناية القانونية", d: "فحص الملكية والصكوك والقيود والتزامات العقار قبل الصفقة." },
        { t: "الإيجار", d: "عقود الإيجار السكنية والتجارية وإنهاؤها والإخلاء ومطالبات الأجرة." },
        { t: "التطوير العقاري", d: "عقود المطورين والبيع على الخارطة وحقوق المشترين ومتطلبات الجهات المنظمة." },
        { t: "الاستثمار والشراكات العقارية", d: "هياكل الاستثمار والشراكة والصناديق العقارية." },
        { t: "المنازعات العقارية", d: "منازعات الملكية والحدود والشراكة والتسليم والعيوب." },
      ],
      faqs: [
        { q: "ما الذي يجب فحصه قبل شراء عقار؟", a: "الصك وسلامة الملكية وغياب الرهون والقيود والاشتراطات التنظيمية وحالة العقار ومطابقة المساحات والحدود." },
        { q: "هل يجوز للمؤجر إنهاء العقد قبل مدته؟", a: "بحسب شروط العقد والأحكام النظامية؛ وقد يتطلب الإنهاء مبررًا وإخطارًا في مدة محددة." },
        { q: "كيف نحمي المشتري في البيع على الخارطة؟", a: "بالتحقق من ترخيص المشروع وآلية حفظ الدفعات والجدول الزمني وغرامات التأخير وضمانات التسليم." },
      ],
    },
    en: {
      title: "Real Estate",
      short: "Sale, lease, development, registration, real-estate investment and disputes.",
      intro: "Real estate is a high-value asset where registration, development, lease and ownership rules meet. We advise owners, developers, investors and tenants to protect the transaction from negotiation through transfer and registration, and manage property disputes.",
      issues: [
        { t: "Sale, purchase and due diligence", d: "Checking title, deeds, encumbrances and the property's obligations before the deal." },
        { t: "Leasing", d: "Residential and commercial leases, termination, eviction and rent claims." },
        { t: "Development", d: "Developer contracts, off-plan sales, buyers' rights and regulators' requirements." },
        { t: "Investment and partnerships", d: "Investment and partnership structures and real-estate funds." },
        { t: "Property disputes", d: "Disputes over title, boundaries, partnership, delivery and defects." },
      ],
      faqs: [
        { q: "What should be checked before buying property?", a: "The title deed, soundness of ownership, absence of mortgages and encumbrances, regulatory requirements, condition, and area and boundaries." },
        { q: "Can a landlord end a lease early?", a: "According to the lease terms and statutory rules; termination may need a justification and notice within a set period." },
        { q: "How do we protect the buyer in an off-plan sale?", a: "By verifying the project permit, how payments are held, the timetable, delay penalties and handover guarantees." },
      ],
    },
  },
  {
    slug: "security-defense",
    services: ["government-contracts", "compliance-governance", "corporate-contracts", "white-collar-aml"],
    articles: ["due-diligence-before-commercial-deal-saudi-arabia", "commercial-contract-review-before-signing", "conflict-of-interest-policy-governance-saudi-arabia"],
    ar: {
      title: "الأمن والدفاع",
      short: "العقود الحكومية والتوطين الصناعي والامتثال والتراخيص لشركات الأمن والدفاع.",
      intro: "تعمل الشركات في الأمن والدفاع ضمن متطلبات امتثال صارمة تتعلق بالتراخيص والتوطين والمشتريات الحكومية وسرية المعلومات. نخدم الموردين والمقاولين والشركاء الأجانب في بناء ملف امتثال متين وعقود محكمة.",
      issues: [
        { t: "المنافسات والعقود الحكومية", d: "التأهيل والعروض والعقود والتنفيذ والمطالبات في المشتريات الحكومية." },
        { t: "التراخيص والتوطين", d: "متطلبات التراخيص والمحتوى المحلي والشراكات مع الجهات الوطنية." },
        { t: "الامتثال والنزاهة", d: "سياسات مكافحة الفساد وتعارض المصالح والعناية بالأطراف الثالثة." },
        { t: "سرية المعلومات والأمن", d: "اتفاقيات عدم الإفصاح وحماية المعلومات الحساسة." },
        { t: "الشراكات والمشاريع المشتركة", d: "هياكل الشراكة مع الشركات الأجنبية ونقل التقنية." },
      ],
      faqs: [
        { q: "ما أهم متطلبات المشاركة في المنافسات الحكومية؟", a: "استيفاء شروط التأهيل وتقديم العرض وفق كراسة الشروط في الموعد، مع الالتزام بنظام المنافسات والمشتريات الحكومية ولوائحه." },
        { q: "هل يمكن الاعتراض على نتيجة منافسة؟", a: "نعم وفق الإجراءات والمدد النظامية المحددة للتظلم، وتُقدَّم الأسباب والمستندات الداعمة." },
        { q: "كيف نحمي المعلومات الحساسة في الشراكة؟", a: "باتفاقية سرية مفصلة وضوابط وصول وإجراءات استرجاع وإتلاف عند انتهاء العلاقة." },
      ],
    },
    en: {
      title: "Security & Defence",
      short: "Government contracts, industrial localisation, compliance and licensing for security and defence companies.",
      intro: "Security and defence companies work under strict compliance requirements on licensing, localisation, government procurement and confidentiality. We help suppliers, contractors and foreign partners build a sound compliance file and tight contracts.",
      issues: [
        { t: "Government tenders and contracts", d: "Pre-qualification, bids, contracts, performance and claims in public procurement." },
        { t: "Licensing and localisation", d: "Licence requirements, local content and partnerships with national entities." },
        { t: "Compliance and integrity", d: "Anti-corruption, conflict-of-interest policies and third-party due diligence." },
        { t: "Confidentiality and security", d: "Non-disclosure agreements and protection of sensitive information." },
        { t: "Partnerships and joint ventures", d: "Partnership structures with foreign companies and technology transfer." },
      ],
      faqs: [
        { q: "What are the main requirements to take part in government tenders?", a: "Meeting pre-qualification, submitting the bid per the tender documents on time, and complying with the Government Tenders and Procurement Law and its regulations." },
        { q: "Can a tender result be challenged?", a: "Yes, under the statutory grievance procedures and time limits, with the grounds and supporting documents." },
        { q: "How do we protect sensitive information in a partnership?", a: "A detailed confidentiality agreement, access controls and return or destruction procedures on termination." },
      ],
    },
  },
  {
    slug: "environment-water",
    services: ["compliance-governance", "government-contracts", "ppp-privatization", "energy-mining"],
    articles: ["commercial-contract-review-before-signing", "force-majeure-exceptional-circumstances-saudi-arabia", "due-diligence-before-commercial-deal-saudi-arabia"],
    ar: {
      title: "البيئة والموارد المائية",
      short: "الامتثال البيئي وتراخيص المياه والتحلية ومشاريع الشراكة والعقود الحكومية.",
      intro: "تتسع أعمال المياه والبيئة في المملكة بمشاريع التحلية والمعالجة وإدارة النفايات والطاقة المتجددة. نساعد المطورين والمشغلين والمستثمرين على فهم متطلبات الامتثال وتنظيم عقود الشراكة وتخصيص المخاطر.",
      issues: [
        { t: "الامتثال البيئي والتراخيص", d: "التصاريح البيئية والالتزامات التشغيلية وتقارير الأثر وإجراءات المخالفات." },
        { t: "مشاريع المياه والتحلية", d: "عقود الإنشاء والتشغيل ونقل الملكية ومشتريات المياه." },
        { t: "الشراكة بين القطاعين", d: "هياكل الشراكة وتخصيص المخاطر والتمويل." },
        { t: "العقود الحكومية", d: "المنافسات والعقود وإدارة التغيير والمطالبات." },
        { t: "المسؤولية والتعويض", d: "المسؤولية عن الأضرار البيئية وإدارة النزاعات." },
      ],
      faqs: [
        { q: "هل يلزم تصريح بيئي قبل بدء المشروع؟", a: "تتطلب كثير من الأنشطة تصريحًا أو موافقة بيئية مسبقة بحسب طبيعة المشروع، ويُحدَّد ذلك مع الجهة المختصة." },
        { q: "من يتحمل مخاطر الطلب في عقود المياه؟", a: "يتحدد بهيكل العقد، وغالبًا ما تُوزَّع المخاطر بين الجهة المتعاقدة والمشغل وفق نموذج الشراكة." },
        { q: "ما عواقب مخالفة الاشتراطات البيئية؟", a: "قد تشمل غرامات وإيقاف النشاط والتزامات المعالجة والتعويض، بحسب جسامة المخالفة." },
      ],
    },
    en: {
      title: "Environment & Water",
      short: "Environmental compliance, water and desalination licensing, partnership projects and government contracts.",
      intro: "Water and environmental work in the Kingdom is expanding through desalination, treatment, waste management and renewable-energy projects. We help developers, operators and investors understand compliance requirements and structure partnership contracts and risk allocation.",
      issues: [
        { t: "Environmental compliance and permits", d: "Environmental permits, operating obligations, impact reports and violation procedures." },
        { t: "Water and desalination projects", d: "Build-operate-transfer contracts and water purchase." },
        { t: "Public–private partnerships", d: "Partnership structures, risk allocation and financing." },
        { t: "Government contracts", d: "Tenders, contracts, change management and claims." },
        { t: "Liability and compensation", d: "Liability for environmental harm and dispute management." },
      ],
      faqs: [
        { q: "Is an environmental permit needed before a project starts?", a: "Many activities need a prior permit or approval depending on the project; confirm with the competent authority." },
        { q: "Who bears demand risk in water contracts?", a: "The contract structure decides; risks are usually split between the contracting authority and the operator under the partnership model." },
        { q: "What follows a breach of environmental requirements?", a: "Possible fines, suspension of activity, remediation duties and compensation, depending on the seriousness of the breach." },
      ],
    },
  },
  {
    slug: "municipal-housing",
    services: ["real-estate-construction", "government-contracts", "ppp-privatization", "disputes-arbitration"],
    articles: ["residential-lease-check-before-signing-saudi-arabia", "commercial-contract-review-before-signing", "arbitration-clause-commercial-contracts-saudi-arabia"],
    ar: {
      title: "البلديات والإسكان",
      short: "عقود الأمانات والبلديات واستثمار الأراضي والتطوير السكني والشراكة مع الجهات الحكومية.",
      intro: "يتعامل المستثمرون والمطورون في قطاع البلديات والإسكان مع عقود استثمار أراضٍ ومشاريع سكنية وخدمات مدن بشراكة الجهات الحكومية. نساعدهم على تقييم العقد والمخاطر وتنفيذ المشروع وحماية حقوقهم.",
      issues: [
        { t: "استثمار الأراضي والمواقع", d: "عقود الاستثمار البلدي وإيجار الأراضي ومدد التطوير والتزامات المستثمر." },
        { t: "التطوير السكني", d: "عقود التطوير والبيع والتسليم وحقوق المستفيدين." },
        { t: "الشراكة مع الجهات الحكومية", d: "اتفاقيات الشراكة وتوزيع المخاطر والعوائد." },
        { t: "الأذونات والتراخيص", d: "رخص البناء والاشتراطات والجهات المختصة." },
        { t: "المنازعات", d: "منازعات العقود الحكومية والبلدية والتحكيم." },
      ],
      faqs: [
        { q: "ما مخاطر عقود استثمار الأراضي البلدية؟", a: "تشمل التزامات التطوير ضمن مدد محددة وغرامات التأخير وأحكام إنهاء العقد، لذا يلزم فحص الشروط قبل التوقيع." },
        { q: "هل يمكن التحكيم في منازعات العقود الحكومية؟", a: "تخضع إمكانية التحكيم لأنظمة المشتريات الحكومية وشروط العقد وموافقة الجهات المختصة، ويُراجع ذلك في كل عقد." },
        { q: "كيف نتعامل مع تأخر الأذونات؟", a: "بتوثيق الطلبات والمراسلات ودراسة أثر التأخير على الالتزامات وإخطار الجهة المتعاقدة وفق العقد." },
      ],
    },
    en: {
      title: "Municipal & Housing",
      short: "Municipal contracts, land investment, residential development and partnerships with government entities.",
      intro: "Investors and developers in municipal and housing work with land-investment contracts, residential projects and city services in partnership with government entities. We help them assess the contract and risks, deliver the project and protect their rights.",
      issues: [
        { t: "Land and site investment", d: "Municipal investment contracts, land leases, development periods and investor obligations." },
        { t: "Residential development", d: "Development, sale and handover contracts and beneficiaries' rights." },
        { t: "Partnership with government entities", d: "Partnership agreements and allocation of risks and returns." },
        { t: "Permits and licences", d: "Building permits, requirements and the competent authorities." },
        { t: "Disputes", d: "Government and municipal contract disputes and arbitration." },
      ],
      faqs: [
        { q: "What are the risks of municipal land-investment contracts?", a: "Development obligations within set periods, delay penalties and termination terms, so conditions must be reviewed before signing." },
        { q: "Can government contract disputes go to arbitration?", a: "It depends on the procurement laws, the contract terms and the competent authority's approval, reviewed contract by contract." },
        { q: "How do we handle delayed permits?", a: "By documenting applications and correspondence, assessing the effect of delay on obligations and notifying the contracting authority under the contract." },
      ],
    },
  },
  {
    slug: "culture-media",
    services: ["intellectual-property", "corporate-contracts", "compliance-governance", "technology-data"],
    articles: ["commercial-contract-review-before-signing", "memorandum-of-understanding-saudi-arabia", "personal-data-protection-obligations-saudi-arabia"],
    ar: {
      title: "الثقافة والإعلام",
      short: "حقوق المؤلف وعقود الإنتاج والمحتوى الرقمي وتراخيص الإعلام والنشر والإعلان.",
      intro: "يقوم الإنتاج الثقافي والإعلامي على الحقوق الفكرية وعقود الإنتاج والتوزيع والترخيص. نساعد المبدعين وشركات الإنتاج والمنصات والناشرين على حماية أعمالهم وتنظيم حقوقهم وضبط التزامات المحتوى.",
      issues: [
        { t: "حقوق المؤلف والحقوق المجاورة", d: "ملكية المصنفات وتسجيلها وتراخيصها وحمايتها من التعدي." },
        { t: "عقود الإنتاج والتوزيع", d: "عقود الإنتاج والمشاركة والتمويل والتوزيع وتقاسم الإيرادات." },
        { t: "المحتوى الرقمي والمؤثرون", d: "عقود التعاون الإعلاني وشروط الإعلان والإفصاح ومسؤولية المحتوى." },
        { t: "التراخيص والمتطلبات التنظيمية", d: "تراخيص النشر والإنتاج والبث ومتطلبات المحتوى." },
        { t: "العلامات والسمعة", d: "حماية الأسماء والعلامات والتعامل مع التشهير والتعدي." },
      ],
      faqs: [
        { q: "كيف نثبت ملكية عمل إبداعي؟", a: "بتوثيق تاريخ الإنشاء وهوية المؤلف والتسجيل لدى الجهة المختصة وعقود نقل الحقوق المكتوبة." },
        { q: "هل نحتاج عقدًا مع صانع محتوى؟", a: "نعم، لتحديد المطلوب ومدة الاستخدام والمقابل وحقوق المحتوى والإفصاح الإعلاني وحالات الإنهاء." },
        { q: "ما الإجراء عند استخدام عملنا دون إذن؟", a: "إثبات الملكية والاستخدام وإنذار المخالف ثم المطالبة بالإزالة والتعويض عبر الإجراءات النظامية." },
      ],
    },
    en: {
      title: "Culture & Media",
      short: "Copyright, production contracts, digital content and media, publishing and advertising licences.",
      intro: "Cultural and media production rests on intellectual-property rights and on production, distribution and licensing contracts. We help creators, production companies, platforms and publishers protect their work, structure their rights and control content obligations.",
      issues: [
        { t: "Copyright and related rights", d: "Ownership, registration, licensing and protection of works against infringement." },
        { t: "Production and distribution contracts", d: "Production, co-production, financing and distribution contracts and revenue sharing." },
        { t: "Digital content and influencers", d: "Advertising collaboration agreements, ad terms, disclosure and content liability." },
        { t: "Licences and regulatory requirements", d: "Publishing, production and broadcast licences and content requirements." },
        { t: "Marks and reputation", d: "Protecting names and marks and dealing with defamation and infringement." },
      ],
      faqs: [
        { q: "How do we prove ownership of a creative work?", a: "By documenting the creation date and author, registration with the competent authority and written assignment contracts." },
        { q: "Do we need a contract with a content creator?", a: "Yes — to fix deliverables, duration of use, fee, content rights, advertising disclosure and termination." },
        { q: "What if our work is used without permission?", a: "Prove ownership and use, send a cease-and-desist notice, then claim removal and compensation through the formal procedures." },
      ],
    },
  },
  {
    slug: "agriculture",
    services: ["corporate-contracts", "compliance-governance", "foreign-investment", "enforcement-recovery"],
    articles: ["commercial-contract-review-before-signing", "force-majeure-exceptional-circumstances-saudi-arabia", "commercial-contract-receivables-saudi-arabia"],
    ar: {
      title: "الزراعة والأمن الغذائي",
      short: "عقود التوريد الزراعي والاستثمار الزراعي والغذاء والتراخيص والتصدير والاستيراد.",
      intro: "يرتبط القطاع الزراعي والغذائي بسلاسل إمداد ومتطلبات سلامة غذائية وتراخيص واستثمارات في الداخل والخارج. نساعد المزارع والمصنّعين والموزعين والمستثمرين على تنظيم عقودهم والامتثال لمتطلبات الجهات المختصة.",
      issues: [
        { t: "عقود التوريد والتوزيع الغذائي", d: "اتفاقيات التوريد والجودة والتسليم والدفع وحقوق الرفض." },
        { t: "التراخيص وسلامة الغذاء", d: "متطلبات تراخيص المنشآت والمنتجات والاشتراطات الصحية." },
        { t: "الاستثمار الزراعي", d: "الشراكات والمشاريع الزراعية والاستثمار داخل المملكة وخارجها." },
        { t: "الاستيراد والتصدير", d: "المتطلبات الجمركية والفسح والمواصفات والعقود الدولية." },
        { t: "المطالبات والتحصيل", d: "تحصيل مستحقات التوريد ونزاعات الجودة." },
      ],
      faqs: [
        { q: "ما أهم بنود عقد توريد منتجات غذائية؟", a: "مواصفات الجودة وشروط التسليم والتخزين وفترة الصلاحية وحق الفحص والرفض وآلية الدفع والتعويض عن العيب." },
        { q: "كيف نتعامل مع شحنة مرفوضة؟", a: "بمراجعة العقد وتقارير الفحص وتوثيق السبب ثم التفاوض على الاستبدال أو الخصم أو الإجراء النظامي." },
        { q: "هل يلزم ترخيص لتصنيع الغذاء؟", a: "نعم، تتطلب المنشآت الغذائية تراخيص واشتراطات صحية من الجهات المختصة قبل التشغيل." },
      ],
    },
    en: {
      title: "Agriculture & Food Security",
      short: "Agricultural supply and investment, food licensing, import and export.",
      intro: "Agriculture and food are tied to supply chains, food-safety requirements, licences and investments at home and abroad. We help farms, manufacturers, distributors and investors structure their contracts and meet the competent authorities' requirements.",
      issues: [
        { t: "Food supply and distribution contracts", d: "Supply, quality, delivery and payment terms and rejection rights." },
        { t: "Licensing and food safety", d: "Facility and product licensing and health requirements." },
        { t: "Agricultural investment", d: "Partnerships and agricultural projects in the Kingdom and abroad." },
        { t: "Import and export", d: "Customs requirements, clearance, specifications and international contracts." },
        { t: "Claims and recovery", d: "Recovering supply receivables and quality disputes." },
      ],
      faqs: [
        { q: "What matters in a food supply contract?", a: "Quality specifications, delivery and storage terms, shelf life, inspection and rejection rights, payment and compensation for defects." },
        { q: "How do we handle a rejected shipment?", a: "Review the contract and inspection reports, document the reason, then negotiate replacement or discount or take formal action." },
        { q: "Is a licence needed to manufacture food?", a: "Yes — food facilities need licences and health requirements from the competent authorities before operating." },
      ],
    },
  },
  {
    slug: "energy-mining",
    services: ["energy-mining", "foreign-investment", "disputes-arbitration", "ppp-privatization"],
    articles: ["arbitration-clause-commercial-contracts-saudi-arabia", "force-majeure-exceptional-circumstances-saudi-arabia", "due-diligence-before-commercial-deal-saudi-arabia"],
    ar: {
      title: "الطاقة والتعدين",
      short: "عقود الطاقة والمرافق والتعدين والتراخيص والاستثمار والتمويل والتحكيم.",
      intro: "يتميز قطاعا الطاقة والتعدين بمشاريع رأسمالية كبيرة وتراخيص دقيقة وعقود طويلة الأجل. نساعد المطورين والمستثمرين والممولين والمقاولين على هيكلة المشاريع وتوزيع المخاطر وإدارة المنازعات.",
      issues: [
        { t: "الترخيص والتصاريح", d: "تراخيص الاستكشاف والتعدين والطاقة والامتثال لشروطها." },
        { t: "عقود المشاريع", d: "عقود الهندسة والمشتريات والإنشاء واتفاقيات شراء الطاقة والتشغيل والصيانة." },
        { t: "التمويل والضمانات", d: "هيكلة تمويل المشاريع والضمانات وحقوق المقرضين." },
        { t: "الاستثمار والشراكات", d: "المشاريع المشتركة والاستثمار الأجنبي ونقل التقنية." },
        { t: "المنازعات والتحكيم", d: "نزاعات المشاريع والتحكيم المحلي والدولي." },
      ],
      faqs: [
        { q: "كيف تُوزَّع المخاطر في عقود المشاريع الكبرى؟", a: "تُوزَّع بين المالك والمقاول والممول بنصوص تفصيلية تتناول التأخير وتغير القوانين والقوة القاهرة وأسعار المواد." },
        { q: "هل يمكن الاتفاق على التحكيم الدولي؟", a: "غالبًا نعم بحسب طبيعة العقد والأطراف، مع مراعاة قابلية تنفيذ حكم التحكيم داخل المملكة." },
        { q: "ما مخاطر الإخلال بشروط الترخيص؟", a: "قد تتضمن إيقاف النشاط أو سحب الترخيص أو الغرامات، ولذا يلزم الامتثال المستمر لشروطه." },
      ],
    },
    en: {
      title: "Energy & Mining",
      short: "Energy, utilities and mining contracts, licensing, investment, finance and arbitration.",
      intro: "Energy and mining involve large capital projects, precise licences and long-term contracts. We help developers, investors, lenders and contractors structure projects, allocate risk and manage disputes.",
      issues: [
        { t: "Licensing and permits", d: "Exploration, mining and energy licences and compliance with their conditions." },
        { t: "Project contracts", d: "EPC contracts, power-purchase agreements and operation and maintenance." },
        { t: "Finance and security", d: "Project-finance structuring, security and lenders' rights." },
        { t: "Investment and partnerships", d: "Joint ventures, foreign investment and technology transfer." },
        { t: "Disputes and arbitration", d: "Project disputes and local and international arbitration." },
      ],
      faqs: [
        { q: "How is risk allocated in major project contracts?", a: "Among owner, contractor and lender through detailed provisions on delay, change in law, force majeure and material prices." },
        { q: "Can international arbitration be agreed?", a: "Often yes depending on the contract and parties, taking into account enforceability of the award within the Kingdom." },
        { q: "What are the risks of breaching licence conditions?", a: "Possible suspension, licence withdrawal or fines, so continuing compliance with its conditions is essential." },
      ],
    },
  },
  {
    slug: "government",
    services: ["government-contracts", "ppp-privatization", "disputes-arbitration", "compliance-governance"],
    articles: ["arbitration-clause-commercial-contracts-saudi-arabia", "commercial-contract-review-before-signing", "conflict-of-interest-policy-governance-saudi-arabia"],
    ar: {
      title: "القطاع الحكومي",
      short: "المنافسات والعقود الحكومية والشراكة بين القطاعين والخصخصة وحوكمة الجهات.",
      intro: "تتعامل الجهات الحكومية والشركات المتعاقدة معها ضمن منظومة محددة للمشتريات والعقود. نقدّم للجهات الحكومية والموردين مشورة في إعداد المنافسات والعقود وإدارة التنفيذ والمطالبات وحوكمة العلاقة التعاقدية.",
      issues: [
        { t: "المنافسات والمشتريات", d: "إعداد وثائق المنافسة والتأهيل وتقييم العروض والترسية والتظلمات." },
        { t: "العقود الحكومية", d: "صياغة العقود وإدارة التغيير والتأخير والغرامات والمطالبات." },
        { t: "الشراكة والخصخصة", d: "هياكل الشراكة بين القطاعين العام والخاص ومتطلبات الخصخصة." },
        { t: "الحوكمة والامتثال", d: "سياسات النزاهة وتعارض المصالح ومتطلبات الشفافية." },
        { t: "المنازعات", d: "تسوية منازعات العقود الحكومية وإجراءات التظلم والتقاضي." },
      ],
      faqs: [
        { q: "ما أبرز مخاطر العقود الحكومية على المورد؟", a: "الغرامات وشروط الإنهاء الإداري والتعديلات الأحادية وتأخر المستخلصات، ولذا تُراجع شروط العقد بعناية قبل التقديم." },
        { q: "هل يمكن التظلم من قرار استبعاد؟", a: "نعم وفق الإجراءات والمدد النظامية، مع تقديم الأسباب والمستندات الداعمة." },
        { q: "ما دور الحوكمة في العلاقة مع الجهات الحكومية؟", a: "تضمن وضوح الصلاحيات والنزاهة وتعارض المصالح وسلامة التوثيق، وتقلل مخاطر المساءلة." },
      ],
    },
    en: {
      title: "Government Sector",
      short: "Tenders and government contracts, public–private partnerships, privatisation and entity governance.",
      intro: "Government entities and the companies contracting with them operate within a defined procurement and contracting system. We advise government bodies and suppliers on preparing tenders and contracts, managing performance and claims, and governing the contractual relationship.",
      issues: [
        { t: "Tenders and procurement", d: "Preparing tender documents, pre-qualification, bid evaluation, award and grievances." },
        { t: "Government contracts", d: "Drafting contracts and managing variation, delay, penalties and claims." },
        { t: "Partnership and privatisation", d: "Public–private partnership structures and privatisation requirements." },
        { t: "Governance and compliance", d: "Integrity policies, conflict of interest and transparency requirements." },
        { t: "Disputes", d: "Resolving government-contract disputes, grievance procedures and litigation." },
      ],
      faqs: [
        { q: "What are the main risks of government contracts for a supplier?", a: "Penalties, administrative termination terms, unilateral amendments and delayed payment certificates — so contract terms are reviewed carefully before bidding." },
        { q: "Can an exclusion decision be challenged?", a: "Yes, under the statutory procedures and time limits, with the grounds and supporting documents." },
        { q: "What role does governance play in dealings with government bodies?", a: "It secures clarity of authority, integrity, conflict-of-interest control and sound documentation, reducing accountability risk." },
      ],
    },
  },
  {
    slug: "family-businesses",
    services: ["family-business", "corporate-contracts", "disputes-arbitration", "mergers-acquisitions"],
    articles: ["shareholders-agreement-saudi-arabia", "shareholder-partner-disputes-saudi-arabia", "heirs-dispute-estate-division-saudi-arabia", "director-manager-liability-saudi-arabia"],
    ar: {
      title: "الشركات العائلية",
      short: "الحوكمة العائلية والتوريث واتفاقيات الشركاء وفض النزاعات والتحول المؤسسي.",
      intro: "الشركة العائلية تجمع بين الملكية والعلاقة الأسرية، ومن أكبر مخاطرها غياب الحوكمة عند الانتقال بين الأجيال. نساعد العائلات على بناء ميثاق وحوكمة واضحة وهياكل ملكية تحفظ استمرار المنشأة وتقلل النزاعات.",
      issues: [
        { t: "ميثاق وحوكمة الأسرة", d: "تنظيم القرار ومجلس الأسرة ودور أفرادها في الملكية والإدارة." },
        { t: "اتفاقيات الشركاء", d: "تنظيم الأرباح والتخارج والتقييم وقيود نقل الحصص." },
        { t: "التوريث وانتقال الملكية", d: "تخطيط انتقال الحصص بين الأجيال وأثر الميراث على المنشأة." },
        { t: "التحول المؤسسي", d: "الانتقال من الإدارة الأسرية إلى الإدارة المؤسسية وتشكيل مجلس الإدارة." },
        { t: "فض النزاعات", d: "تسوية خلافات الشركاء بالتفاوض أو الوساطة أو التحكيم." },
      ],
      faqs: [
        { q: "هل يلزم ميثاق عائلي؟", a: "ليس إلزاميًا نظامًا، لكنه من أهم أدوات الحوكمة لأنه يحدد القواعد قبل أن تنشأ الخلافات ويحفظ استمرارية المنشأة." },
        { q: "كيف نمنع دخول طرف خارجي كشريك؟", a: "بنصوص في عقد التأسيس أو اتفاقية الشركاء تتضمن حق الشفعة وقيودًا على التنازل وآلية تقييم الحصة." },
        { q: "ما الحل عند اختلاف الورثة على إدارة الشركة؟", a: "التفاوض ثم الوساطة أو التحكيم إن وُجد شرط، ثم الإجراءات النظامية، مع تنظيم الإدارة مؤقتًا حفاظًا على النشاط." },
      ],
    },
    en: {
      title: "Family Businesses",
      short: "Family governance, succession, shareholder agreements, dispute resolution and institutionalisation.",
      intro: "A family business joins ownership and family ties, and its biggest risk is the lack of governance when it passes between generations. We help families build a charter, clear governance and ownership structures that preserve the business and reduce disputes.",
      issues: [
        { t: "Family charter and governance", d: "Organising decisions, the family council and each member's role in ownership and management." },
        { t: "Shareholder agreements", d: "Profit policy, exit, valuation and restrictions on transferring shares." },
        { t: "Succession and transfer of ownership", d: "Planning share transfers between generations and the effect of inheritance on the business." },
        { t: "Institutionalisation", d: "Moving from family to institutional management and forming a board." },
        { t: "Dispute resolution", d: "Resolving partner disputes by negotiation, mediation or arbitration." },
      ],
      faqs: [
        { q: "Is a family charter necessary?", a: "Not mandatory by law, but one of the most important governance tools: it sets the rules before disputes arise and preserves continuity." },
        { q: "How do we stop an outsider becoming a partner?", a: "Provisions in the articles or shareholders' agreement: pre-emption rights, transfer restrictions and a share-valuation mechanism." },
        { q: "What if heirs disagree on running the company?", a: "Negotiation, then mediation or arbitration if a clause exists, then formal procedure — with interim management arrangements to keep the business running." },
      ],
    },
  },
  {
    slug: "nonprofit-endowments",
    services: ["endowments-nonprofits", "compliance-governance", "corporate-contracts", "personal-data-protection"],
    articles: ["conflict-of-interest-policy-governance-saudi-arabia", "memorandum-of-understanding-saudi-arabia", "personal-data-protection-obligations-saudi-arabia"],
    ar: {
      title: "القطاع غير الربحي والأوقاف",
      short: "تأسيس الجمعيات والمؤسسات الأهلية والأوقاف والحوكمة والامتثال وعقود الشراكة والتبرعات.",
      intro: "تتطلب المنشآت غير الربحية والأوقاف حوكمة شفافة وامتثالًا لأنظمة الجمعيات والمؤسسات الأهلية والأوقاف. نساعدها على التأسيس وتنظيم الحوكمة وعقود الشراكة وجمع التبرعات وإدارة الأصول الوقفية.",
      issues: [
        { t: "التأسيس والتسجيل", d: "تأسيس الجمعيات والمؤسسات الأهلية وإعداد اللوائح الأساسية." },
        { t: "الأوقاف", d: "إنشاء الوقف وصياغة وثيقته وإدارة النظارة واستثمار الأصول الوقفية." },
        { t: "الحوكمة والامتثال", d: "سياسات الحوكمة وتعارض المصالح والتقارير والإفصاح." },
        { t: "الشراكات والتبرعات", d: "اتفاقيات الشراكة والجهات المانحة وضوابط جمع التبرعات وإنفاقها." },
        { t: "العقود والموارد البشرية", d: "عقود الخدمات والمتطوعين والعاملين." },
      ],
      faqs: [
        { q: "كيف يُؤسَّس وقف نظاميًا؟", a: "بصياغة وثيقة وقف واضحة تحدد الموقوف والمصرف والنظارة وشروط الواقف، ثم توثيقها واتباع الإجراءات لدى الجهة المختصة." },
        { q: "ما أهم ضوابط جمع التبرعات؟", a: "الحصول على التصاريح المطلوبة والالتزام بالأغراض المعلنة والإفصاح والرقابة على الإنفاق وفق الأنظمة." },
        { q: "كيف نتجنب تعارض المصالح في مجلس الإدارة؟", a: "بسياسة مكتوبة للإفصاح والامتناع عن التصويت وسجل للتعارضات ومراجعة دورية." },
      ],
    },
    en: {
      title: "Non-Profit & Endowments (Awqaf)",
      short: "Establishing associations, foundations and endowments, governance, compliance, partnership and donation contracts.",
      intro: "Non-profits and endowments need transparent governance and compliance with the laws on associations, foundations and endowments. We help them incorporate, structure governance, partnership contracts and fundraising, and manage endowment assets.",
      issues: [
        { t: "Incorporation and registration", d: "Establishing associations and foundations and preparing their basic regulations." },
        { t: "Endowments (Awqaf)", d: "Creating the endowment, drafting the deed, administering trusteeship and investing endowment assets." },
        { t: "Governance and compliance", d: "Governance policies, conflicts of interest, reporting and disclosure." },
        { t: "Partnerships and donations", d: "Partnership agreements, donors and rules for raising and spending donations." },
        { t: "Contracts and staffing", d: "Service, volunteer and employment contracts." },
      ],
      faqs: [
        { q: "How is an endowment established lawfully?", a: "By drafting a clear deed setting out the endowed asset, beneficiaries, trusteeship and the founder's conditions, then documenting it and following the competent authority's procedures." },
        { q: "What are the key rules on raising donations?", a: "Obtaining required permits, honouring the stated purposes, disclosure and oversight of spending under the regulations." },
        { q: "How do we avoid board conflicts of interest?", a: "A written disclosure and recusal policy, a register of conflicts and periodic review." },
      ],
    },
  },
];

export const sectorBySlug = (slug: string) => sectors.find((s) => s.slug === slug);
